services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: marty
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgre_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    container_name: django_app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --chdir /Excercize Excercize.wsgi:application --bind 0.0.0.0:8001"
    environment:
      DEBUG: "1"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgre_database
      DB_USER: marty
      DB_PASSWORD: 1234
    depends_on:
      - db
    ports:
      - "8001:8001"
    volumes:
      - .:/Excercize
      - ./staticfiles:/Excercize/staticfiles
volumes:
  postgres_data:
