# Generated by Django 5.1.4 on 2025-01-14 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(error_messages='Kérlek valid e-mail címet adj meg!', max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
