# Generated by Django 5.1.4 on 2025-01-14 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(error_messages={'null': 'A mező nem lehet üres!'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, error_messages={'null': 'A mező nem lehet üres!'}, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(error_messages={'null': 'A mező nem lehet üres!'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(error_messages={'null': 'A mező nem lehet üres!'}, max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(error_messages={'null': 'A mező nem lehet üres!'}),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Kérlek valid e-mail címet adj meg!', 'null': 'A mező nem lehet üres!'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('tester', 'Tester')], error_messages={'invalid': 'Csak developer, designer, manager vagy tester választható!', 'null': 'A mező nem lehet üres!'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(error_messages={'null': 'A mező nem lehet üres!'}, max_length=100),
        ),
    ]
