# Generated by Django 5.1.4 on 2025-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_address_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(error_messages={'blank': 'A mező nem lehet üres!', 'null': 'A mező nem lehet üres!'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, error_messages={'blank': 'A mező nem lehet üres!', 'null': 'A mező nem lehet üres!'}, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(error_messages={'blank': 'A mező nem lehet üres!', 'null': 'A mező nem lehet üres!'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(error_messages={'blank': 'A mező nem lehet üres!', 'null': 'A mező nem lehet üres!'}, max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(error_messages={'blank': 'A mező nem lehet üres!', 'null': 'A mező nem lehet üres!'}),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('tester', 'Tester')], error_messages={'blank': 'A mező nem lehet üres!', 'invalid': "Csak 'developer', 'designer', 'manager' vagy 'tester' választható!", 'null': 'A mező nem lehet üres!'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(error_messages={'blank': 'A mező nem lehet üres!', 'null': 'A mező nem lehet üres!'}, max_length=100),
        ),
    ]
