# Generated by Django 5.1.4 on 2025-01-15 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_company_address_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="The phone number must begin with the prefix '+36' or '06' and contain 9 digits.", regex='^(?:\\+36|06)\\d{9}$')]),
        ),
    ]
